# примеры API-запросов

# получение объявлений
GET http://localhost:8000/api/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://localhost:8000/api/advertisements/
Content-Type: application/json
Authorization: Token 2f690e3b98b07d771e1818f745d9a126c9a25760

{
  "title": "Кроссовки Adidas",
  "description": "45 р-р, новые"
}

###

# попытка поменять объявление
PATCH http://localhost:8000/api/advertisements/3/
Content-Type: application/json
Authorization: Token 81666f1d1ba12ca04b51421ae6a238a23f8bd6fc

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET http://localhost:8000/api/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по дате
GET http://localhost:8000/api/advertisements/?created_at_after=2022-04-17
Content-Type: application/json

###

DELETE http://localhost:8000/api/advertisements/30/
Authorization: Token 2f690e3b98b07d771e1818f745d9a126c9a25760
