# Generated by Django 4.0.3 on 2022-03-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_studentsteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsteacher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='school.student'),
        ),
    ]
