GET http://localhost:8000/api/sensors/
Content-Type: application/json

###

# создание датчика
POST http://localhost:8000/api/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH http://localhost:8000/api/sensors/2/
Content-Type: application/json

{
  "description": "Датчик перенесен в сауну"
}

###

# добавление измерения
POST http://localhost:8000/api/measurements/
Content-Type: application/json

{
  "id_sensor": 3,
  "temperature": 23.1
}

###

# получение информации по датчику
GET http://localhost:8000/api/sensors/1/
Content-Type: application/json
